/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.prog2.labs;

import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author Admin
 */
public class addNewBook extends javax.swing.JFrame {

    /**
     * Creates new form addNewBook
     */
    ResourceBundle messages;
    

    public addNewBook() {
        initComponents();
        messages = ResourceBundle.getBundle("messages", Locale.getDefault());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_lbl = new javax.swing.JLabel();
        sn_lbl = new javax.swing.JLabel();
        bookTitle_lbl = new javax.swing.JLabel();
        authorlabel = new javax.swing.JLabel();
        pubshLabel = new javax.swing.JLabel();
        pricelabel = new javax.swing.JLabel();
        quantlabel = new javax.swing.JLabel();
        snTextField = new javax.swing.JTextField();
        titleTextField = new javax.swing.JTextField();
        authorTextField = new javax.swing.JTextField();
        publisherTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        quntyTextField = new javax.swing.JTextField();
        submit_btnn = new javax.swing.JButton();
        langToggleButton = new javax.swing.JToggleButton();
        back_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Librarian - Add New Book");

        title_lbl.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        title_lbl.setText("Add New Book");

        sn_lbl.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        sn_lbl.setText("SN:");

        bookTitle_lbl.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        bookTitle_lbl.setText("Title: ");

        authorlabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        authorlabel.setText("Author:");

        pubshLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        pubshLabel.setText("Publisher:");

        pricelabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        pricelabel.setText("Price");

        quantlabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        quantlabel.setText("Quantity:");

        submit_btnn.setText("Add Book");
        submit_btnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnnActionPerformed(evt);
            }
        });

        langToggleButton.setText("FR");
        langToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                langToggleButtonActionPerformed(evt);
            }
        });

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bookTitle_lbl)
                            .addComponent(sn_lbl)
                            .addComponent(authorlabel)
                            .addComponent(pubshLabel)
                            .addComponent(pricelabel)
                            .addComponent(quantlabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(snTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(publisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quntyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_btn)
                        .addGap(126, 126, 126)
                        .addComponent(submit_btnn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(langToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(title_lbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sn_lbl)
                    .addComponent(snTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookTitle_lbl)
                    .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorlabel))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pubshLabel)
                    .addComponent(publisherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pricelabel)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quntyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submit_btnn)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(langToggleButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(back_btn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        viewLibrarian vl = new viewLibrarian();
        vl.show();
        this.dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void submit_btnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnnActionPerformed
        // TODO add your handling code here:
        LibraryController lc = new LibraryController();
        try {
            lc.addBook(snTextField.getText(), titleTextField.getText(), authorTextField.getText(), publisherTextField.getText(), Float.parseFloat(priceTextField.getText()), Integer.parseInt(quntyTextField.getText()));
        } catch (Exception ex) {
            logInLibrarian lil = new logInLibrarian();
            lil.showDialog("Couldn't Add New Book", "ERROR: " + ex.getMessage());
        }
    }//GEN-LAST:event_submit_btnnActionPerformed

    private void langToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_langToggleButtonActionPerformed
        // TODO add your handling code here:
        if (langToggleButton.isSelected()) {
            //french
            messages = ResourceBundle.getBundle("messages", Locale.FRENCH);
            updateAddBookTexts();

        } else {
            //english
            messages = ResourceBundle.getBundle("messages", Locale.ENGLISH);
            updateAddBookTexts();
        }
    }//GEN-LAST:event_langToggleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addNewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addNewBook().setVisible(true);
            }
        });
    }

  private void updateAddBookTexts() {
    authorlabel.setText(messages.getString("authorlabel"));
    back_btn.setText(messages.getString("back_btn"));
    bookTitle_lbl.setText(messages.getString("bookTitle_lbl"));
    pricelabel.setText(messages.getString("pricelabel"));
    pubshLabel.setText(messages.getString("pubshLabel"));
    quantlabel.setText(messages.getString("quantlabel"));
    sn_lbl.setText(messages.getString("sn_lbl"));
    submit_btnn.setText(messages.getString("submit_btnn"));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorTextField;
    private javax.swing.JLabel authorlabel;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel bookTitle_lbl;
    private javax.swing.JToggleButton langToggleButton;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel pricelabel;
    private javax.swing.JTextField publisherTextField;
    private javax.swing.JLabel pubshLabel;
    private javax.swing.JLabel quantlabel;
    private javax.swing.JTextField quntyTextField;
    private javax.swing.JTextField snTextField;
    private javax.swing.JLabel sn_lbl;
    private javax.swing.JButton submit_btnn;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JLabel title_lbl;
    // End of variables declaration//GEN-END:variables
}
